# 开发环境配置文件
server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/start?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678